// flow-typed signature: 0b1cdb0c9dcd06af726671a13328d7ca
// flow-typed version: <<STUB>>/ansi-escapes_v1.4.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-escapes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-escapes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ansi-escapes/index' {
  declare module.exports: $Exports<'ansi-escapes'>;
}
declare module 'ansi-escapes/index.js' {
  declare module.exports: $Exports<'ansi-escapes'>;
}
