// flow-typed signature: 5266730f332b2831ea1a079f7c23d36d
// flow-typed version: <<STUB>>/download_v5.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'download'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'download' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'download/index' {
  declare module.exports: $Exports<'download'>;
}
declare module 'download/index.js' {
  declare module.exports: $Exports<'download'>;
}
