// flow-typed signature: 192d80c0c0f606531a09944edb5fb2a1
// flow-typed version: <<STUB>>/find-node-modules_v^1.0.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-node-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-node-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-node-modules/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-node-modules/index' {
  declare module.exports: $Exports<'find-node-modules'>;
}
declare module 'find-node-modules/index.js' {
  declare module.exports: $Exports<'find-node-modules'>;
}
declare module 'find-node-modules/test.js' {
  declare module.exports: $Exports<'find-node-modules/test'>;
}
