// flow-typed signature: 48ba6b64eb6f6e28aa585aa78a0cfcfe
// flow-typed version: <<STUB>>/got_v7.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'got'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'got' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'got/index' {
  declare module.exports: $Exports<'got'>;
}
declare module 'got/index.js' {
  declare module.exports: $Exports<'got'>;
}
