// flow-typed signature: 5c3a55e9f7719b94b74313f16351a8ee
// flow-typed version: <<STUB>>/heroku-debug-4.0.0_vfile:test/heroku-debug/4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-debug-4.0.0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-debug-4.0.0' {
  declare module.exports: any;
}
