// flow-typed signature: b4e9f0f5de43a21985aa6e215b58dad9
// flow-typed version: <<STUB>>/heroku-hello-world-build_v0.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-hello-world-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-hello-world-build' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-hello-world-build/hello' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-hello-world-build/hello.js' {
  declare module.exports: $Exports<'heroku-hello-world-build/hello'>;
}
