// flow-typed signature: 8cd89cd02b2a67c21df9af5c58ee4fb8
// flow-typed version: <<STUB>>/heroku-pg-extras_v^1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-pg-extras'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-pg-extras' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-pg-extras/commands/bloat' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/blocking' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/cache_hit' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/calls' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/extensions' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/fdwsql' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/index_size' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/index_usage' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/locks' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/long_running_queries' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/mandelbrot' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/outliers' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/records_rank' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/seq_scans' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/stats_reset' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/table_indexes_size' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/table_size' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/total_index_size' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/total_table_size' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/unused_indexes' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/user_connections' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/commands/vacuum_stats' {
  declare module.exports: any;
}

declare module 'heroku-pg-extras/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-pg-extras/commands/bloat.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/bloat'>;
}
declare module 'heroku-pg-extras/commands/blocking.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/blocking'>;
}
declare module 'heroku-pg-extras/commands/cache_hit.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/cache_hit'>;
}
declare module 'heroku-pg-extras/commands/calls.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/calls'>;
}
declare module 'heroku-pg-extras/commands/extensions.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/extensions'>;
}
declare module 'heroku-pg-extras/commands/fdwsql.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/fdwsql'>;
}
declare module 'heroku-pg-extras/commands/index_size.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/index_size'>;
}
declare module 'heroku-pg-extras/commands/index_usage.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/index_usage'>;
}
declare module 'heroku-pg-extras/commands/locks.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/locks'>;
}
declare module 'heroku-pg-extras/commands/long_running_queries.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/long_running_queries'>;
}
declare module 'heroku-pg-extras/commands/mandelbrot.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/mandelbrot'>;
}
declare module 'heroku-pg-extras/commands/outliers.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/outliers'>;
}
declare module 'heroku-pg-extras/commands/records_rank.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/records_rank'>;
}
declare module 'heroku-pg-extras/commands/seq_scans.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/seq_scans'>;
}
declare module 'heroku-pg-extras/commands/stats_reset.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/stats_reset'>;
}
declare module 'heroku-pg-extras/commands/table_indexes_size.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/table_indexes_size'>;
}
declare module 'heroku-pg-extras/commands/table_size.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/table_size'>;
}
declare module 'heroku-pg-extras/commands/total_index_size.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/total_index_size'>;
}
declare module 'heroku-pg-extras/commands/total_table_size.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/total_table_size'>;
}
declare module 'heroku-pg-extras/commands/unused_indexes.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/unused_indexes'>;
}
declare module 'heroku-pg-extras/commands/user_connections.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/user_connections'>;
}
declare module 'heroku-pg-extras/commands/vacuum_stats.js' {
  declare module.exports: $Exports<'heroku-pg-extras/commands/vacuum_stats'>;
}
declare module 'heroku-pg-extras/index' {
  declare module.exports: $Exports<'heroku-pg-extras'>;
}
declare module 'heroku-pg-extras/index.js' {
  declare module.exports: $Exports<'heroku-pg-extras'>;
}
declare module 'heroku-pg-extras/lib/util.js' {
  declare module.exports: $Exports<'heroku-pg-extras/lib/util'>;
}
