// flow-typed signature: ec9d4ebf9d4fd460a97b28ec806cddbb
// flow-typed version: <<STUB>>/heroku-kafka_v2.9.8/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-kafka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-kafka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-kafka/commands/configure' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/consumer_groups_create' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/consumer_groups_destroy' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/consumer_groups' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/credentials_rotate' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/fail' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/index' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/info' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_compaction' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_create' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_destroy' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_info' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_replication_factor' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_retention_time' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_tail' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics_write' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/topics' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/upgrade' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/wait' {
  declare module.exports: any;
}

declare module 'heroku-kafka/commands/zookeeper' {
  declare module.exports: any;
}

declare module 'heroku-kafka/lib/clusters' {
  declare module.exports: any;
}

declare module 'heroku-kafka/lib/debug' {
  declare module.exports: any;
}

declare module 'heroku-kafka/lib/fetcher' {
  declare module.exports: any;
}

declare module 'heroku-kafka/lib/host' {
  declare module.exports: any;
}

declare module 'heroku-kafka/lib/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-kafka/commands/configure.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/configure'>;
}
declare module 'heroku-kafka/commands/consumer_groups_create.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/consumer_groups_create'>;
}
declare module 'heroku-kafka/commands/consumer_groups_destroy.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/consumer_groups_destroy'>;
}
declare module 'heroku-kafka/commands/consumer_groups.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/consumer_groups'>;
}
declare module 'heroku-kafka/commands/credentials_rotate.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/credentials_rotate'>;
}
declare module 'heroku-kafka/commands/fail.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/fail'>;
}
declare module 'heroku-kafka/commands/index.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/index'>;
}
declare module 'heroku-kafka/commands/info.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/info'>;
}
declare module 'heroku-kafka/commands/topics_compaction.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_compaction'>;
}
declare module 'heroku-kafka/commands/topics_create.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_create'>;
}
declare module 'heroku-kafka/commands/topics_destroy.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_destroy'>;
}
declare module 'heroku-kafka/commands/topics_info.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_info'>;
}
declare module 'heroku-kafka/commands/topics_replication_factor.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_replication_factor'>;
}
declare module 'heroku-kafka/commands/topics_retention_time.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_retention_time'>;
}
declare module 'heroku-kafka/commands/topics_tail.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_tail'>;
}
declare module 'heroku-kafka/commands/topics_write.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics_write'>;
}
declare module 'heroku-kafka/commands/topics.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/topics'>;
}
declare module 'heroku-kafka/commands/upgrade.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/upgrade'>;
}
declare module 'heroku-kafka/commands/wait.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/wait'>;
}
declare module 'heroku-kafka/commands/zookeeper.js' {
  declare module.exports: $Exports<'heroku-kafka/commands/zookeeper'>;
}
declare module 'heroku-kafka/lib/clusters.js' {
  declare module.exports: $Exports<'heroku-kafka/lib/clusters'>;
}
declare module 'heroku-kafka/lib/debug.js' {
  declare module.exports: $Exports<'heroku-kafka/lib/debug'>;
}
declare module 'heroku-kafka/lib/fetcher.js' {
  declare module.exports: $Exports<'heroku-kafka/lib/fetcher'>;
}
declare module 'heroku-kafka/lib/host.js' {
  declare module.exports: $Exports<'heroku-kafka/lib/host'>;
}
declare module 'heroku-kafka/lib/shared.js' {
  declare module.exports: $Exports<'heroku-kafka/lib/shared'>;
}
