// flow-typed signature: 7a568263a99f0da6c4f21a80503fdfef
// flow-typed version: <<STUB>>/heroku-debug-5.0.3_vfile:test/heroku-debug/5.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-debug-5.0.3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-debug-5.0.3' {
  declare module.exports: any;
}
