// flow-typed signature: bc16cd00f180a70560b0afdd2279c8c6
// flow-typed version: <<STUB>>/heroku-cli-test_v0.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-cli-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-cli-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'heroku-cli-test/index' {
  declare module.exports: $Exports<'heroku-cli-test'>;
}
declare module 'heroku-cli-test/index.js' {
  declare module.exports: $Exports<'heroku-cli-test'>;
}
