// flow-typed signature: 6ba366a1d7a342a849dc116a14bfe90c
// flow-typed version: <<STUB>>/heroku-debug-5.0.2_vfile:test/heroku-debug/5.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-debug-5.0.2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-debug-5.0.2' {
  declare module.exports: any;
}
