// flow-typed signature: 64b714ca436cab292df54ef9e355e9f7
// flow-typed version: <<STUB>>/klaw-sync_v2.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'klaw-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'klaw-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'klaw-sync/klaw-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'klaw-sync/klaw-sync.js' {
  declare module.exports: $Exports<'klaw-sync/klaw-sync'>;
}
