// flow-typed signature: daf5726e9e0e44da541afa8559d31003
// flow-typed version: <<STUB>>/klaw-sync_v1.1.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'klaw-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'klaw-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'klaw-sync/klaw-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'klaw-sync/klaw-sync.js' {
  declare module.exports: $Exports<'klaw-sync/klaw-sync'>;
}
