// flow-typed signature: 7e7ee7b6f343471bb30246c1ec4d0c00
// flow-typed version: <<STUB>>/klaw_v^2.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'klaw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'klaw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'klaw/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'klaw/src/index.js' {
  declare module.exports: $Exports<'klaw/src/index'>;
}
