// flow-typed signature: c14a29d11d0da6eb8903ff8e3bc22d8f
// flow-typed version: <<STUB>>/levenshtein_v^1.0.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'levenshtein'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'levenshtein' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'levenshtein/lib/levenshtein' {
  declare module.exports: any;
}

declare module 'levenshtein/test/test' {
  declare module.exports: any;
}

declare module 'levenshtein/vendor/qunit-extras/qunit-extras' {
  declare module.exports: any;
}

declare module 'levenshtein/vendor/qunit/qunit/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'levenshtein/lib/levenshtein.js' {
  declare module.exports: $Exports<'levenshtein/lib/levenshtein'>;
}
declare module 'levenshtein/test/test.js' {
  declare module.exports: $Exports<'levenshtein/test/test'>;
}
declare module 'levenshtein/vendor/qunit-extras/qunit-extras.js' {
  declare module.exports: $Exports<'levenshtein/vendor/qunit-extras/qunit-extras'>;
}
declare module 'levenshtein/vendor/qunit/qunit/qunit.js' {
  declare module.exports: $Exports<'levenshtein/vendor/qunit/qunit/qunit'>;
}
