// flow-typed signature: bbf80774ff206991e763edd51b6ff174
// flow-typed version: <<STUB>>/lodash.uniqby_v4.x/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.uniqby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.uniqby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.uniqby/index' {
  declare module.exports: $Exports<'lodash.uniqby'>;
}
declare module 'lodash.uniqby/index.js' {
  declare module.exports: $Exports<'lodash.uniqby'>;
}
