// flow-typed signature: 427c09a405b5f5bd5aea18f61e45234f
// flow-typed version: <<STUB>>/lodash.maxby_v4.x/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.maxby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.maxby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.maxby/index' {
  declare module.exports: $Exports<'lodash.maxby'>;
}
declare module 'lodash.maxby/index.js' {
  declare module.exports: $Exports<'lodash.maxby'>;
}
