// flow-typed signature: aa8462e402c8c6f38a6f35e44bc587ca
// flow-typed version: <<STUB>>/rwlockfile_v1.3.3/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rwlockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rwlockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rwlockfile/rwlockfile' {
  declare module.exports: any;
}

declare module 'rwlockfile/test/init' {
  declare module.exports: any;
}

declare module 'rwlockfile/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rwlockfile/rwlockfile.js' {
  declare module.exports: $Exports<'rwlockfile/rwlockfile'>;
}
declare module 'rwlockfile/test/init.js' {
  declare module.exports: $Exports<'rwlockfile/test/init'>;
}
declare module 'rwlockfile/test/test.js' {
  declare module.exports: $Exports<'rwlockfile/test/test'>;
}
