// flow-typed signature: 5f05c6fdc5f6c926e7ba11b15b783643
// flow-typed version: <<STUB>>/rwlockfile_v^1.3.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rwlockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rwlockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rwlockfile/rwlockfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rwlockfile/rwlockfile.js' {
  declare module.exports: $Exports<'rwlockfile/rwlockfile'>;
}
