// flow-typed signature: f2fb6795dc8c292df18575b6c01878ef
// flow-typed version: <<STUB>>/standard_v10.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard/bin/cmd' {
  declare module.exports: any;
}

declare module 'standard/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard/bin/cmd.js' {
  declare module.exports: $Exports<'standard/bin/cmd'>;
}
declare module 'standard/index' {
  declare module.exports: $Exports<'standard'>;
}
declare module 'standard/index.js' {
  declare module.exports: $Exports<'standard'>;
}
declare module 'standard/options.js' {
  declare module.exports: $Exports<'standard/options'>;
}
