// flow-typed signature: 730d42693667cfb0b96f697543916191
// flow-typed version: <<STUB>>/tmp_v0.0.31/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp/lib/tmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp/lib/tmp.js' {
  declare module.exports: $Exports<'tmp/lib/tmp'>;
}
