// flow-typed signature: fad9ad0a77c57163719a9b79e702e8b9
// flow-typed version: <<STUB>>/@heroku/linewrap_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@heroku/linewrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@heroku/linewrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@heroku/linewrap/linewrap' {
  declare module.exports: any;
}

// Filename aliases
declare module '@heroku/linewrap/linewrap.js' {
  declare module.exports: $Exports<'@heroku/linewrap/linewrap'>;
}
